apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-cpu-limit
  labels:
    app.kubernetes.io/name: sleep-cpu-limit
    app.kubernetes.io/instance: sleep-cpu-limit
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: dummy
    app.kubernetes.io/part-of: admission-webhook-example
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sleep-cpu-limit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sleep-cpu-limit
    spec:
      containers:
      - name: sleep-cpu-limit
        image: curlimages/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 8
            memory: 200Mi
          requests:
            cpu: 8
            memory: 100Mi
